Repository amber-lang/amber, pull requests merged in 2024-07, with the labels that each got.

#234 add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#245 feat(compile): add Amber version, fix #181
  Cargo.lock
  Cargo.toml
  src/compiler.rs
  src/header.sh
Labels: enhancement

#268 fix(std): download and curl
  src/std/main.ab
Labels: bug

#309 feat(std): env methods with arguments
  src/std/env.ab
Labels: enhancement

#128 Integrate shfmt
  README.md
  src/compiler.rs
  src/main.rs
  src/modules/formatter.rs
  src/modules/imports/import.rs
  src/modules/mod.rs
  src/tests/formatter.rs
  src/tests/mod.rs
  src/tests/stdlib.rs
  src/tests/validity.rs
Labels: enhancement
